Vagrant.configure("2") do |config|

  config.vm.box = "marcoaltieri/ubuntu-desktop-16.04-64bit"
  config.disksize.size = "15GB"

  config.vm.provider "virtualbox" do |vb|
    vb.gui = true
  end

  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get remove libappstream3 -y
  SHELL

  config.vm.provision "ansible_local" do |ansible|
    ansible.playbook = "install.yml"
  end
end
