Vagrant.configure("2") do |config|

  SDN_PATH = "/home/vagrant/warsztaty_sdn"

  config.vm.box = "ubuntu/xenial64"
  config.vm.define "warsztaty-sdn"
  config.vm.synced_folder "../", SDN_PATH
  config.vm.network "forwarded_port", guest: 80, host: 8081
  config.vm.provider "virtualbox" do |vb|
    vb.name = "warsztaty-sdn"
    vb.memory = 2048
    vb.cpus = 2
  end

  config.vm.provision "shell", inline: <<-SHELL
    echo "ubuntu:ubuntu" | sudo chpasswd
  SHELL
  config.vm.provision "ansible_local" do |ansible|
    ansible.playbook = "#{SDN_PATH}/install.yml"
  end

end
