Vagrant.configure("2") do |config|

  config.vm.box = "marcoaltieri/ubuntu-desktop-16.04-64bit"


  # your network.
  # config.vm.network "public_network"


  config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
    vb.gui = true
  #
  #   # Customize the amount of memory on the VM:
  #   vb.memory = "1024"
  end
  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get remove libappstream3 -y

  SHELL


  config.vm.provision "ansible_local" do |ansible|
    ansible.playbook = "install.yml"
  end
end
