---

- hosts: all
  tasks:
    - name: Update and upgrade apt packages
      become: true
      apt:
        upgrade: yes
        update_cache: yes

    - name: Add latest Python and Ansible PPAs
      shell: "add-apt-repository {{ item }} -y"
      become:  true
      with_items:
        - ppa:jonathonf/python-3.6
        - ppa:ansible/ansible

    - name: install components
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      with_items:
        - python3.6
        - python-pip
        - python-dev
        - python3-pip
        - python3-dev
        - build-essential
        - docker.io
      become: true

    - name: piping
      pip:
        name: "{{ item }}"
        state: present
      with_items:
        - docker
      become: true

    - name: Add user to docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes
      become: true

    - name: Set locales
      blockinfile:
        block: |
          export LC_ALL="en_US.UTF-8"
          export LC_CTYPE="en_US.UTF-8"
        path: "{{ ansible_env.HOME }}/.bashrc"
