Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/xenial64"
  config.vm.define "polibuda-sdn"
  config.vm.synced_folder "save/", "/home/vagrant/Desktop/save"
  config.vm.provider "virtualbox" do |vb|
    vb.name = "polibuda-sdn"
    vb.gui = true
    vb.memory = 2048
    vb.cpus = 2
  end

  config.vm.provision "shell", inline: <<-SHELL
    echo "ubuntu:ubuntu" | sudo chpasswd
  SHELL
  config.vm.provision "ansible_local" do |ansible|
    ansible.playbook = "install.yml"
  end

end
