---
- name: uninstall docker-py
  pip:
    name: '{{ item }}'
    state: absent
  with_items:
    - docker
    - docker-py

- name: install docker
  pip:
    name: '{{ item }}'
    state: present
  with_items:
    - docker

- name: add iptables
  shell: "iptables -I DOCKER-ISOLATION -j RETURN"
  become: true




