---
- name: Ensures /opt/sdn dir exists
  file:
    path: '/home/vagrant/save/sdn'
    state: directory

- name: Create docker compose
  template:
    src: docker-compose.yml.j2
    dest: "/opt/sdn/docker-compose.yml"


