- hosts: all
  become: yes
  vars:
    text: 'ala ma kota'

  tasks:
  #http://docs.ansible.com/ansible/latest/modules/list_of_files_modules.html
  - name: create file
    file:
      path: /etc/test/my_file
      state: touch

  #http://docs.ansible.com/ansible/latest/modules/shell_module.html
  - name: write text
    shell: 'echo {{ text }} >> /etc/test/my_file'

  #http://docs.ansible.com/ansible/latest/modules/lineinfile_module.html
  - name: write text
    lineinfile:
      path: /etc/test/my_file
      line: '{{ text }}'

  - name: cat dir
    shell: 'cat /etc/test/my_file'
    register: result

  #http://docs.ansible.com/ansible/latest/modules/debug_module.html
  - name: show cat dir
    debug:
      msg: '{{result.stdout}}'



