---
- name: Ensures /opt/sdn dir exists
  file: path=/opt/sdn  state=directory

- name: install compose
  pip:
    name: docker-compose
    state: present

- name: Create docker compose
  template:
    src: docker-compose.yml.j2
    dest: "{{inventory_dir}}/docker-compose.yml"

- name: Run docker compose
  docker_service:
    project_src: '.'
    files: "{{inventory_dir}}/docker-compose.yml"
    state: present

- name: Add sdn dir to global.config
  ini_file:
    path: "{{inventory_dir}}/sdn/config/global.conf"
    section: agent
    option: sdn_path
    value: "{{inventory_dir}}/sdn/"
