---

- hosts: localhost
  gather_facts: no
  become: true
  tasks:
    - import_tasks: compose.yml

    - name: start http server
      shell: "python3 -m http.server 8080 &"
      args:
        chdir: /home/vagrant/warsztaty_sdn/sdn/controller/webui/dist
