---
- hosts: localhost
  gather_facts: no
  become: true
  tasks:
    - name: Manually create the initial virtualenv
      command: "python3.6 -m venv {{inventory_dir}}/venv/"

    - name: Install requirements
      pip:
        requirements: '{{inventory_dir}}/sdn/{{item}}/requirements.txt'
        virtualenv: "{{inventory_dir}}/venv/"
      with_items:
        - controller
        - router
        - agent

    - name: Install robotrequirements
      pip:
        requirements: '{{inventory_dir}}/robot-tests/requirements.txt'
        virtualenv: "{{inventory_dir}}/venv/"
